package com.example.bemyhelper;

public enum Disabilities {
    SLIGHT_AUDITIVE_DIFFICULTY,
    SEVERE_AUDITIVE_DIFFICULTY,
    SLIGHT_COGNITIVE_DIFFICULTY,
    SEVERE_COGNITIVE_DIFFICULTY,
    COMMUNICATION_DIFFICULTY,
    SLIGHT_MOTOR_DIFFICULTY,
    SEVERE_MOTOR_DIFFICULTY,
    SLIGHT_VISUAL_DIFFICULTY,
    SEVERE_VISUAL_DIFFICULTY,
}
